- hosts: localhost
   # Become root user
  become: yes
   # List of tasks to be executed
  tasks:
  - community.vmware.vmware_host_config_manager:
     hostname: '{{ vcenter.hostname }}'
     username: '{{ vcenter.username }}'
     password: '{{ vcenter.password }}'
     esxi_hostname: '{{ esxi.hostname }}'
     validate_certs: no
     options:
       'Config.HostAgent.log.level': 'verbose'
    delegate_to: localhost
