
- hosts: localhost
   # Become root user
  become: yes
   # List of tasks to be executed
  tasks:
  - community.vmware.vmware_host_config_manager:
     hostname: '{{ vcenter_hostname }}'
     username: '{{ vcenter_username }}'
     password: '{{ vcenter_password }}'
     validate_certs: no
     esxi_hostname: '{{ esxi_hostname }}'
     options:
       'Config.HostAgent.log.level': 'verbose'
    delegate_to: localhost
