- hosts: localhost
   # Become root user
  become: yes
   # List of tasks to be executed
  tasks:
  - ansible.builtin.shell: ansible-galaxy collection install community.vmware
  - ansible.builtin.shell: pip3 install pyvmomi
  - ansible.builtin.shell: ansible-playbook demarrerVM.yml --extra-vars "hostname_vcenter="{{hostname_vcenter}}""
    delegate_to: localhost
