- hosts: localhost
   # Become root user
  become: yes
   # List of tasks to be executed
  tasks:
  - ansible.builtin.shell: ansible-galaxy collection install community.vmware
  - ansible.builtin.shell: pip3 install pyvmomi
  - ansible.builtin.debug:
    msg: "{{ vcenter_hostname }}"
  - ansible.builtin.shell: ansible-playbook demarrerVM.yml
    delegate_to: localhost
