- name: Lance les jobs vmware
  debug: "hostname du vcenter: {{ hostname_vcenter }}"
  hosts: localhost
   # Become root user
  become: yes
   # List of tasks to be executed
  tasks:
   - ansible.builtin.shell: ansible-galaxy collection install community.vmware
   - ansible.builtin.shell: pip3 install pyvmomi
   - ansible.builtin.shell: ansible-playbook demarrerVM.yml
  delegate_to: localhost
