- hosts: localhost
   # Become root user
  become: yes
   # List of tasks to be executed
  tasks:
  - community.vmware.vmware_guest_powerstate:
      hostname: ''
      username: ''
      password: ''
      validate_certs: no
      folder: "/DatacenterAppart/"
      name: ""
      state: powered-off
      #esxi_hostname: ''
    delegate_to: localhost
    register: deploy
