- hosts: localhost
   # Become root user
  become: yes
   # List of tasks to be executed
  tasks:
   - name: Demmarer une vm
     debug:
      msg: "{{ hostname_vcenter }}"
   - ansible.builtin.shell: ansible-galaxy collection install community.vmware
   - ansible.builtin.shell: pip3 install pyvmomi
   - ansible.builtin.shell: ansible-playbook demarrerVM.yml --extra-vars "hostname_vcenter={{ hostname_vcenter }} username_vcenter={{ username_vcenter }} password_vcenter={{ password_vcenter }} emplacementVM={{ emplacementVM }} nomVM={{ nomVM }}"
