- hosts: localhost
   # Become root user
  become: yes
   # List of tasks to be executed
  tasks:
  - community.vmware.vmware_guest_powerstate:
      hostname: 'vcenter-appart.private.local'
      username: 'administrator@vsphere.local'
      password: 'Mw4-31_83CK2020'
      validate_certs: no
      folder: "/DatacenterAppart/"
      name: "ClientWindowsAppart"
      state: powered-off
      #esxi_hostname: 'esx-appart.private.local'
    delegate_to: localhost
    register: deploy
