
- hosts: localhost
   # Become root user
  become: yes
   # List of tasks to be executed
  gather_facts: no
  collections:
  - community.vmware.vmware_host_config_manager
  tasks:
   - name: Manage Log level setting for an ESXi host
    community.vmware.vmware_host_config_manager:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      esxi_hostname: '{{ esxi_hostname }}'
      validate_certs: no
      options:
          'Config.HostAgent.log.level': 'verbose'
    delegate_to: localhost
